spring:
  application:
    name: service-eureka-jtv
  security:
    user:
      name: root
      password: root

server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://root:root@localhost:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 1000
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000
  instance:
    lease-renewal-interval-in-seconds: 1
    hostname: localhost